version: '3'
services:
  sb-matching-server:
    container_name: matching_server
    platform: linux/x86_64
    build:
      context: ./sb_matching_server
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    tty: true
    ports:
      - 8000:8000
    volumes:
      - ./sb_matching_server:/app
    depends_on:
      - db

  db:
    container_name: matching_db
    platform: linux/x86_64
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data      

  matching-app:
    container_name: matching-app
    build:
      context: ./matching-app
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./matching-app:/usr/src/app:cached
    tty: true
    ports:
      - "3000:3000"

  mock:
    container_name: mock-server
    platform: linux/x86_64
    build: ./mock_server
    ports:
      - '3002:3000'
    volumes: 
      - ./mock_server/db.json:/data/db.json
    command: json-server --watch db.json --host 0.0.0.0

  plantuml-server:
    container_name: plantuml
    image: plantuml/plantuml-server
    restart: always
    ports:
      - "8080:8080"