version: '3'
services:
#  sb-matching-server:
#    container_name: matching_server
#    platform: linux/x86_64
#    build:
#      context: ./sb-matching-server
#      dockerfile: Dockerfile
#    ports:
#      - 8000:8000
#    volumes:
#      - ./sb-matching-server:/app
#    depends_on:
#      - db
#
#  db:
#    container_name: matching_db
#    platform: linux/x86_64
#    image: mysql:5.7.22
#    restart: always
#    environment:
#      MYSQL_DATABASE: main
#      MYSQL_USER: root
#      MYSQL_PASSWORD: password
#      MYSQL_ROOT_PASSWORD: password
#    volumes:
#      - .dbdate:/var/lib/mysql
#    ports:
#      - 3306:3306

  matching-app:
    container_name: matching-app
    build:
      context: ./sb-matching-app
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./sb-matching-app:/usr/src/app:cached
    tty: true
#    command: sh sh-c "cd matching-app && yarn start"
    ports:
      - "3000:3000"